### ISSUE TITLE
GLKZ Instrument Respons for HH channels missing prior to 2021-10-24

### ISSUE THREAD

**Issue by SquirrelKnight** [GeoNet/help#110]
Hello, I noticed that instrument responses for the HH channels are missing for station GLKZ prior to 2021-10-24 from the Obspy FDSN webservice. Please see the attached image. I believe this information was previously available, at least as of August 2022.

<img width="491" alt="Screenshot 2023-06-22 at 9 54 19 PM" src="https://github.com/GeoNet/help/assets/41596863/8339a0b7-92c2-44d1-8523-0085785f4ffa">

**Comment by salichon** [comment]
Hi @SquirrelKnight good to hear from you :) 
https://service.geonet.org.nz/fdsnws/station/1/query?network=NZ&station=GLKZ&level=channel&format=text&channel=?H? 
is confirmed
the metadata volume for GLKZ weak motion is broken - this gonna be fixed
thanks for noticing

**Comment by SquirrelKnight** [comment]
Thanks @salichon ! Good to hear from you too :) Glad to hear that the fix is on the way!

**Comment by salichon** [comment]
- [ ]  check for :
https://service.geonet.org.nz/fdsnws/station/1/query?network=NZ&station=GLKZ&level=channel&format=text&channel=?H? 
upon recent change in the GLKZ metadata

**Comment by salichon** [comment]
- merged by March 2024 -should be fixed
