### ISSUE TITLE
Sites missing from GeoNet sensor map

### ISSUE THREAD

**Issue by calum-chamberlain** [GeoNet/help#114]
Currently the [GeoNet sensor map](https://www.geonet.org.nz/data/network/sensor/search) is only showing Air Pressure sensors when all station types are selected. I have seen this on multiple computers now over the last two days and at least one of my students is seeing the same.

I am using Firefox (I guess this might be a browser related problem?), and can provide more details as needed.

**Comment by calum-chamberlain** [comment]
Sites are also missing for me viewed from Chrome.

**Comment by mnaguit** [comment]
Hi @calum-chamberlain , I'm using Chrome. I checked the sensor map, this is the result:
![image](https://github.com/GeoNet/help/assets/34523675/c21242e3-0e76-42d6-8b4b-12c0c2c9fe35)

**Comment by calum-chamberlain** [comment]
Possibly a Linux only issue or browser version issue then.  I only get air pressure for chrome and Firefox.

**Comment by calum-chamberlain** [comment]
On Firefox for android nothing at all is plotted.

**Comment by elidana** [comment]
thanks @calum-chamberlain  for raising it!

agree that it looks like a mobile phone issue (linux browsers works fine for me too, chrome&firefox).

I have the same issue on my iPhone (only air pressure data show)

Model/iOS is: `iPhone SE 16.6.1`

@mnaguit , @calum-chamberlain can you please add your model/version as well? might help with troubleshooting

**Comment by calum-chamberlain** [comment]
Firefox 117.0.1 running on Manjaro (Arch) Linux:
![image](https://github.com/GeoNet/help/assets/10913395/e1cb871a-714f-4f93-902f-b15b1e717361)

Chrome Version 117.0.5938.88 on Manjaro (Arch) Linux:
![image](https://github.com/GeoNet/help/assets/10913395/76415576-5c63-4679-8fe8-c2e9667bb4d7)

**Comment by calum-chamberlain** [comment]
On firefox on Windows (version 102.12.0esr) no sites are plotted.

In case it matters, these are all running on the same (VUW) network.

**Comment by mnaguit** [comment]
Same here. No sites plotted using Samsung phone S20+ Android 13 and Pixel Android 10.
I can go ask my hubby to check his phone too. 😆

**Comment by elidana** [comment]
odd about the browser @calum-chamberlain ,
I have tried Chrome and Firefox on my Fedora laptop and they both works fine
(I have the last official release of both browsers)

whereas I can replicate your issue on my mobile phone. thanks for adding the sw/version info!

**Comment by mnaguit** [comment]
Hi @calum-chamberlain, can you please check if the sensor map is working now on your end? thanks!

**Comment by calum-chamberlain** [comment]
Yup, looks good for me now! Thanks

For my own curiosity, did you work out the cause?

**Comment by sue-h-gns** [comment]
there was a change to metadata deployed that exposed an issue in the code that failed to deal with null values
