### ISSUE TITLE
Seismic-products site is down

### ISSUE THREAD

**Issue by mswidan** [GeoNet/help#119]
Hi

https://[data.geonet.org.nz](https://data.geonet.org.nz/seismic-products/strong-motion/)/seismic-products/strong-motion/ and all sub sites are down, please check.

I tried two PCs, each using two different browsers but same issue. Most likely server down.

Appreciate your prompt fix.

 Cheers,
Moustafa
![Screenshot 2024-01-15 152940](https://github.com/GeoNet/help/assets/156630097/1d8ba5ae-75cc-4cf8-96ea-37534b83a21a)

**Comment by staylorofford** [comment]
Hi @mswidan,

Thank you for raising this. We are looking into the issue now and will let you know via this ticket when it is resolved.

**Comment by staylorofford** [comment]
Hi @mswidan, the site is now back online.

Please comment here if you have any further issues.

Thanks.
