### ISSUE TITLE
RSAM & SSAM thumbnails not updating

### ISSUE THREAD

**Issue by KTJacobs** [GeoNet/help#125]
Kia ora 

It seems that the RSAM & SSAM page thumbnails aren't updating regularly (https://www.geonet.org.nz/volcano/rsamssam).    The thumbnails are really useful for doing a quick scan of activity and getting a broader sense of weather impacts etc.    However, all of the thumbnails appear to be from April 8th.   I realized as I went to look at a few intersting sites and they looked much different when the larger indivdual station plot came up.   The realtime data still comes up when you look at an individual station, so processing appears intact.    What is the configured refresh rate on the thumbnails?  It would be great if this was daily or smaller. 

Images below contain computer time stamp for reference.
Thumbnail from page: 
![image](https://github.com/user-attachments/assets/6934490e-ffef-4484-bebb-19e343e37003)
Individual large plot: 
![image](https://github.com/user-attachments/assets/bc3fc19b-aa6b-464c-a859-386157f30334)

Thanks

**Comment by elidana** [comment]
hello @KTJacobs ! Thanks a lot for notifying us about this issue!

Thanks to our wonderful engineers, this has now been fixed, and thumbnails are up to date with latest data.

**Comment by KTJacobs** [comment]
Awesome!  Thank you!!

**Comment by KTJacobs** [comment]
@elidana Now the timestamps on all the RSAM thumbnails and larger images are from July 31st?

**Comment by elidana** [comment]
hei thanks @KTJacobs !

it got me as well, but the date you refer to indicates the start of the time window

the plots are up to date and in sync now (the bug was corrected yesterday)

![image](https://github.com/user-attachments/assets/8bd3098c-e662-46b8-8431-9d1b75c69dec)
![image](https://github.com/user-attachments/assets/fcec0468-afee-441e-ae8e-55e23d820abf)

**Comment by KTJacobs** [comment]
Of course!  Thank you @elidana  !!

**Comment by elidana** [comment]
the real thanks go to our master jedi! ;-)

**Comment by KTJacobs** [comment]
Many thanks to the Jedi as well!  Great to have these back up to date.
