### ISSUE TITLE
Felt report error, when trying to submit from iOS app

### ISSUE THREAD

**Issue by quiffman** [GeoNet/help#17]
As reported [via twitter](https://twitter.com/redsezz/status/781995347862106112).

![User error report](https://pbs.twimg.com/media/Cto0nOHUEAAdycb.jpg)

**Comment by carolinelittle** [comment]
There are a few emails in info@geonet that mirror this.

**Comment by junghao** [comment]
I think the problem comes from an existing identity created before we removed "login required". Cognito keeps those identity's status as "login required". 
Though we've removed the authentication but those identities's status remains unchanged.

**Comment by junghao** [comment]
After deleted all those logined identities in Cognito now it's working well.
Reopen this issue when there are more complaints.
