### ISSUE TITLE
Strong motion evt and text files

### ISSUE THREAD

**Issue by carolinelittle** [GeoNet/help#18]
I'm helping a user with old raw, triggered strong motion data from 2005.

There are two files for each event, an evt and txt file. Are these the same data but different formats? There's not much in the text file. 

If they're different, can someone point me to a way he can convert the .evt file to text?

This is the quake he's looking at:

ftp://ftp.geonet.org.nz/strong/raw/altus/2005/2005.183/2005.183.0446.15.TACS.03366.evt 
ftp://ftp.geonet.org.nz/strong/raw/altus/2005/2005.183/2005.183.0446.18.TACS.03366.txt

**Comment by ozym** [comment]
The TXT file was used when comms were very slow. Basically it's a summary of the event and was sent first, the full data in the EVT file was then sent.

It was meant to be used for alerting etc.

**Comment by ozym** [comment]
Depends, could try the V1A formatted files or there are tools from Kinemetrics.  We also have MiniSEED but I'm not sure that would help.

**Comment by carolinelittle** [comment]
It's too small a quake to have made any data in the /Proc files (I think!). 

Thanks! This might help him then: 
http://www.kinemetrics.com/p-151-SMA.aspx

**Comment by ozym** [comment]
or http://wiki.kmi.com/wiki/images/5/58/K2ASCII.zip

**Comment by ozym** [comment]
May need sign in from KMI to see it though.

**Comment by carolinelittle** [comment]
Thanks all, @nbalfour has also done a write up of possible tools. I'll send him the options.
