### ISSUE TITLE
data recovery issues

### ISSUE THREAD

**Issue by ozym** [GeoNet/help#22]
_Following the recent Kaikoura earthquakes we have been busy recovering and validating data. This ticket is to document any known problems._

### Outstanding 
* ~KIKS -- Kaikoura South~ -- **Data from this site has been recovered -- was comms fault**

### Problems
* KHZ -- Kahutara -- **The instrument at this site had a hardware fault which means the 200Hz continuous data was not being stored locally - however the 50Hz continuous data is available  (this site is not a triggered site).**
* LSRC -- Lake Sumner Road -- **This instrument appears to have failed prior to the event.**
* KLDS -- Kikiwa Line Depot -- **Comms is very slow so will take longer to recover data from this site**
* ~SCAC -- Scargill -- **Comms is very slow to this site**~
* ~TOKS -- Te Oka Bay Road -- **Comms is very slow to this site**~

### Missed expected triggers
These sites did not trigger for one reason or another. However, they do record continuously onto disk. We are working on recovering this data were available.
* BOWS -- Bowen Street Turnbull House
* KPOC -- Kaiapoi
* LNBS -- Naenae Bowling Club
* MKVS --Makara Village
* NBSS -- St Bernadettes (Lower Hutt)
* RCBS -- Redcliffs Borehole -- **There may have been a problem with the sensor at this site**
* TAIS -- Taita School
* TRTS -- Torrens Tce Wellington
* UHSS -- Upper Hutt Primary School
* VUWS -- Victoria University Law School

Where possible we will try and reproduce the triggered data from the continuous recordings.

**Comment by elidana** [comment]
### new Cgps installations
Need to re create daily files for the first day (or force the creation if raw2daily complains for too few epochs).  Hourly files are ok
Might be due to synching not yet started, so will need to check tomorrow morning if that was the case
- [ ] sedd 319 (2016-11-15)
- [ ] wra1 daily files (from 319)
- [ ] lrr1  daily files (from 320)
