### ISSUE TITLE
Is there an Alert API that links to the Tsunami Alert network that I can use for my own web app?

### ISSUE THREAD

**Issue by teverth** [GeoNet/help#27]
Hi, I am assisting some students of mine (Year 8!!, Mercury Bay Area School, Whitianga) with the realization of their idea: Make Smoke Alarms turn on when there is a Tsunami Alert. We lately had a 'test' of the Whitianga Tsunami alert system at 2am on the night of the Kaikoura quake, but many people did not hear the sirens!

I made for them an Internet of Things Wifi Connected tiny Arduino compatible controller that at the moment turns the fire alarm on and off based on a test website of my own that permits us to issue an 'alarm', upon which the smoke alarms fitted with the device in homes turn on. We use this chip: https://www.adafruit.com/product/2821 and it works like a charm and turns a standard NZ Smoke Alarm on when my test alert website sets an alarm state to "on".  The chip polls the site once a minute.

The next step would be to link our prototype via an API to 'real data'. Is there an official API to link to the NZ Tsunami warning system in some way?

**Comment by nbalfour** [comment]
Hi, 
Firstly it sounds like an great project you are working on with your students.
Please note that GeoNet does give Tsunami Warnings. This is up to MCDEM and local CDEM groups and  I do not know if there is an API that they use for this.  GeoNet and GNS Science provide scientific advice to MCDEM. 
If you would like to work with your students on GeoNet data, such as earthquake notifications, you can use the GeoNet API.  Here is a link http://api.geonet.org.nz/ 
Thanks
