### ISSUE TITLE
Address missing from drop-down list

### ISSUE THREAD

**Issue by MarkDotBlair** [GeoNet/help#31]
I wanted to submit a Felt report, but your list does not show any version of my address, which is 4/36 Queen Street, Mount Victoria, Wellington.

**Comment by MarkDotBlair** [comment]
This is on your website https://felt.geonet.org.nz/

**Comment by carolinelittle** [comment]
Hi Mark, you're right, it doesn't recognise your address for some reason. It's fine with 34 Queen Street, Mount Vic - and we aggregate the addresses, so I'd suggest using your neighbour's address. 

Sorry about this. We are working on a building our own search with a LINZ database, so hopefully we can fix these type of issues in the future (we currently use Google).

@sorennh or @bpeng can you shed any light?

**Comment by MarkDotBlair** [comment]
OK, thanks, it's not just me then :-)

Best wishes sorting it.

Cheers,
Mark

**Comment by Tumoana** [comment]
Yea me too. 2/139 Wadestown road, Wadestown, Wellington 6012. Google aint googling enough :)

**Comment by carolinelittle** [comment]
Hi @Tumoana, yes, you're in the same boat. Google doesn't know that 139 is more than one house. It'll accept 139 Wadestown Road, which will work fine with our aggregation of locations.

**Comment by Niteowlnz** [comment]
Hi   same for me 10 Goodman Drive , Motueka

**Comment by sara-page** [comment]
Hi @Niteowlnz  sorry for the delay.  if you use 11 Goodman Drive, it will work.
