### ISSUE TITLE
Feedback: Styling tweaks on Recent Quakes.

### ISSUE THREAD

**Issue by ScopeyNZ** [GeoNet/help#39]
Just some feedback about the recent quakes page:

The `<hr>` tags add quite a bit of unnecessary white space to the page. You can see much more with no visual downsides by removing the horizontal rules. For example:

![image](https://user-images.githubusercontent.com/3260989/28196584-c0854bea-68a5-11e7-8dde-76e68e5027be.png)

Additionally, the right hand side coloured bar (`div.media-left`) seems to be disproportionately bigger than the little map of NZ?

I was looking around for a Github project for the website so I could draft a PR but I assume it's closed source.

Thanks, and great work with the new site - looks nice.

**Comment by carolinelittle** [comment]
Thanks for the feedback @ScopeyNZ and sorry for no reply until now! 

User testing of the coloured bar showed that for a section of our users it needs to be quite fat for visibility. However I do agree that there is a lot of white space between each quake. 

I'll pass this on to our devs.
