### ISSUE TITLE
White Island eruption download example has incorrect DOY

### ISSUE THREAD

**Issue by rumachan** [GeoNet/help#43]
aws s3 sync s3://gnss.highrate.data/ /download_directory/ --exclude "*" --include "*/2016/253/RGW*" --no-sign-request
is given as the syntax to download White Island 2016 eruption data, but the correct DOY is 256 not 253. DOY 253 has no data on any kind.

**Comment by staylorofford** [comment]
There seems to have been some mistranslation in the instructions of the dates. I'll check these and correct them. Thanks!
