### ISSUE TITLE
Different notifications for alerts and news

### ISSUE THREAD

**Issue by bytesnz** [GeoNet/help#51]
I think it would be good to have (and be able to set up) different notifications for alerts and for news on the apps (Android). For example, a black icon for news and a red icon for alerts would help easily differentiate between them. Being able to set up different sound notifications would also be really handy.

Thanks for the great app.

**Comment by carolinelittle** [comment]
Hi @bytesnz thanks for the feedback. This is an interesting suggestion. I'll pass it along to our User Experience person and ask them to explore this.
