### ISSUE TITLE
Velocity model questions

### ISSUE THREAD

**Issue by nbalfour** [GeoNet/help#7]
These questions are from a student at VUW regarding the velocity model we use with NonLinLoc. 

Is the velocity model used my NonLinLoc a true 3D model in that, it was not a 2D model projected in 3D space? 

If it is a true 3D velocity model in a NonLinLoc friendly format, is that velocity model available for use to others, say me (VUW student)? 

If so, where would i be able to obtain a copy? 

@salichon @kfenaugh @ozym

**Comment by rumachan** [comment]
The model is available on ftp.geonet.org,nz/seiscomp/nll/3drx Not sure who put it there.

Of course it a real 3D model! Donna Eberhart-Phillips work. I'm sure someone has the reference.

**Comment by salichon** [comment]
hi ,
 it s a SRL 2010 vol81 Nr 6 By Donna Eberhardt-Philips  et al doi 10.1785

**Comment by salichon** [comment]
i guess the 3D files are available too using the online material

**Comment by salichon** [comment]
link is here http://dx.doi.org/10.1785/gssrl.81.6.992

**Comment by nbalfour** [comment]
Thanks for your help @rumachan and @salichon
