### ISSUE TITLE
Downloading data from QCCS and DUWZ

### ISSUE THREAD

**Issue by ChChKate** [GeoNet/help#70]
Hi. I am looking into 3 earthquake events in 2016. I have accessed the data and charts via ftp://ftp.geonet.org.nz/strong/processed/2016 but there is no data from the strong sensor at Queen Charlotte College or the D'Urville Accelerometer and others.  How do I get hold of this data? The specific event is mainly 2016p140897 but also 2016p105478 and 2016p198476.
Would appreciate any help. Cheers, Kate.

**Comment by JonoHanson** [comment]
Answered via email (June 18th, 2020)
