### ISSUE TITLE
Earthquake notification by email

### ISSUE THREAD

**Issue by iaintw** [GeoNet/help#76]
hello I want like you to setup a earthquake notification services on emails please

**Comment by elidana** [comment]
Dear @iaintw 

we do not provide earthquake notifications via email. 

One option we have in place for you to get earthquake notifications would be using the GeoNet App, if you have a mobile phone. The app is available for Iphone, Android, etc.

If you would like to discuss that further, we would need a bit more context around this request or we might be able to point you to alternative ways to get automatic notification. In that case could you please write an email to info@geonet.org.nz ?

Thanks,

Elisabetta
